project_id = "eyuehdefoedxcunxiyvb"

[functions.seed-test-users]
verify_jwt = false

[functions.seed-production-data]
verify_jwt = false

[functions.studio-import-initial-users]
verify_jwt = false

[functions.studio-cleanup-users]
verify_jwt = false

[functions.submit-quiz-answer]
verify_jwt = true

[functions.update-phone]
verify_jwt = true
